### ISSUE TITLE
Add the ability to configure multiple environments

### ISSUE THREAD

**Issue by rtrox** [rtrox/mssqlcli#59]
Would love to see the ability to run multiple environments via config file, something like this:

```yaml
default:
    username: blah
    password: blah
    ... etc ...

dev:
    username: blah
    password: blah

staging:
    username: blah
    password: blah
```

With the addition to a ```--environment```,```-e``` option to specify a non-default environment during execution. A normal query would look like this:

```bash
mssqlcli query ~/sql_queries/my_query.sql  # "default" config
mssqlcli -e dev query ~/sql_queries/my_query.sql  # Instead hit the dev environment.
```

**Comment by bmanojlovic** [comment]
is there any specific reason you have used yaml as configuration DSL?
I would suggest use of ini based configuration as it already supported natively for what you require.
here is simple example, tell me what you think :). (and this should be supported on all platforms by design)

```
import os.path
import sys # arguments parsing...
try:
    import ConfigParser as configparser  # Py2
except ImportError:
    import configparser

config = configparser.RawConfigParser()
config.read(os.path.join (os.path.expanduser("~"),'.msscli.conf'))

@click.option('--environment', '-e',
    default=config.get('default','default_connection')
    help='Which environment to use')

user =  config.get(environment,'user')
pw =  config.get(environment,'password')

print ("connection to xxx with user={username},password={password}").format(
             username=user,password=pw)
```
with simple configuration as this
```
[default]
default_connection = production

[production]
username = blah1
password = halb1

[dev]
username = blah2
password = halb2
```

**Comment by rtrox** [comment]
Hey @bmanojlovic,

Thanks for the response. I had chosen YAML for a couple reasons:

#### Merged Hashes

One of the bigger reasons was actually due to the expectation of having multiple environments. YAML has the concept of "merged hashes" which lets you do something like this:

```YAML
defaults: &defaults
    username: USE_KEYRING("LDAPUser")
    password: USE_KEYRING("LDAPPass")
    server: MY_PROD.example.com
    windows_authentication: true
    domain: EXAMPLE
    app_name: local_login

dev:
    <<: *defaults
    server: MY_DEV.example.com

staging:
    <<: *defaults
    server: MY_STAGING.example.com
    domain: EXAMPLE_STAGING
    password: plaintext_staging
```
That's obviously a convenience thing, and I'm not really hugely attached to it as keyring provides a fair amount of abstraction of shared values anyway. So I could be convinced away from YAML with a strong enough argument.

#### ConfigParser API
I'm really not a fan of the ConfigParser API, I get a little frustrated that they chose to create a datatype with it's own functions for retrieving data (```config.get(section, key)```) rather than unmarshalling to a `sict`. I've heard ```ConfigObj``` is better, but I haven't done any work with it to know for sure. If you're really deadset on ini style configuration, I think that would be the library I would prefer to look into.

#### INI Environment Support
As far environments being supported by default, I'm not sure I really agree there, ini configs simply change the top level key to a "section", rather than a dict key, which to me is just a style choice regarding the writing of the config files themselves. from a programmatic consumption perspective, they're virtually identical:
```python
# YAML
config[environment].get("username")

# ConfigParser
config.get(environment, "username")
```

#### Pros for INI
The big positive I see for INI-style configuration is that it is noticably simpler to programmatically edit single values in a config file (which is helpful for #43). That being said YAML can be unmarshalled to a file as well, so that's really a toss-up.


#### Final Thoughts

All that being said, Either way we'll be asking users to re-write their configuration files at least a small amount for this feature. I'm not hugely opposed to switching to INI style config if you feel strongly about it, but a few notes on implementation:

- If we're switching to INI-style config, I'd prefer to avoid ConfigParser, as it's a pain in the neck.
- As your example code sits, it will break the ability to specify an alternate config file, as the config object is loaded outside the cli function, So it will be necessary to change the ```--environment``` default to a string (```default="default"), and instead load the config from the config_file variable inside the function.
- In either event (YAML or INI), we need to ensure there is code to recognize an old-style config and warn the user that the config file needs to be updated.

**Comment by rtrox** [comment]
Additionally, INI doesn't really play well with nested data structures. For example, in YAML we can do this:

```YAML
default:
    username: blah
    password: blah
    server: blah
    driver: sqlalchemy
    extra_kwargs:
        timeout: 100
        isolation_level: "READ UNCOMMITTED"
```

In INI, this really isn't well supported (```ConfigObj 4``` and the ```INI``` library seem to support it, ConfigParser does not). Even where it is supported, it get's a bit ugly:
```INI
    [default]
        username = blah
        password = blah
        server = blah
        driver = sqlalchemy
        [[extra_kwargs]]
            timeout = 100
            isolation_level = "READ UNCOMMITTED"
```
